### ISSUE TITLE
Footer links to twitter

### ISSUE THREAD

**Issue by jeroen** [ropensci-org/rotemplate#103]
The template footer still has a bird icon with a link to the ropensci twitter.

**Comment by maelle** [comment]
good catch! fixed on main, but it'll only be deployed when you're back as the Docker image build is manually triggered or did I get this wrong?

**Comment by jeroen** [comment]
Thanks! I have deployed the image and triggered a rebuild for alle the docs 🚀

**Comment by maelle** [comment]
@jeroen btw are there docs of how to deploy the image, in case I want to do it myself next time?

**Comment by jeroen** [comment]
You need to trigger this workflow: https://github.com/r-universe-org/build-docs/actions/workflows/build.yml
