### ISSUE TITLE
why do we put everything on the right

### ISSUE THREAD

**Issue by maelle** [ropensci-org/rotemplate#107]
@jeroen do you remember why we decided to put all menu items on the right?

https://github.com/r-lib/pkgdown/pull/2421 reminded me of this.

**Comment by jeroen** [comment]
No I don't remember. I guess just a design choice.

**Comment by maelle** [comment]
do you still think it's the best design? I have no opinion (apart from that bug, that also appears on small screen no matter where articles are placed anyway)
