### ISSUE TITLE
ropensci theme broken with latest pkgdown

### ISSUE THREAD

**Issue by jeroen** [ropensci-org/rotemplate#108]
Our current theme does not work with the new pkgdown. It looks like our theme assumes jQuery is included by pkgdown, but this is not (or no longer?) the case. See: https://docs.ropensci.org/rzmq/

**Comment by jeroen** [comment]
That didn't fix it.

**Comment by maelle** [comment]
jquery is supposed to be added by {{{headdeps}}} and is in docs/deps but not included

**Comment by maelle** [comment]
deps/ is not created

**Comment by maelle** [comment]
https://github.com/r-lib/pkgdown/pull/2395

**Comment by maelle** [comment]
pkgdown assumes we're using BS version 3
