### ISSUE TITLE
Bug Report: Errors in the citation pages

### ISSUE THREAD

**Issue by JiaxiangBU** [ropensci-org/rotemplate#11]
![image](https://user-images.githubusercontent.com/15884785/55049823-ca38b880-5088-11e9-82af-06134ebc6dd0.png)

See this pages, in the bibtex content, there is no `year` arguement, so the year argument in the printed citation is `????` , any way to fix it?

**Comment by maelle** [comment]
Thanks! I've just added a year to the CITATION. I only created the citation to test the display, but it's probably better to have a year.
