### ISSUE TITLE
New pkgdown issues

### ISSUE THREAD

**Issue by jeroen** [ropensci-org/rotemplate#112]
A few test pages:
 - https://docs.ropensci.org/magick/ (search box is gone?)
 - https://docs.ropensci.org/jagstargets/ 
 - https://docs.ropensci.org/dynamite/articles/dynamite_priors.html (math seems ok??)
 - https://docs.ropensci.org/unrtf/ (looks ok?)
 - https://docs.ropensci.org/mctq/ (no search box, alignment of navbar seems weird?)

Also there is an issue with the favicons. In the previous version we used common favicons on docs.ropensci.org e.g.
 - https://docs.ropensci.org/apple-touch-icon.png
 - https://docs.ropensci.org/favicon-32x32.png

And so on. However the new page has favicons in the pkgdown site, but those are missing:

```
Writing to: /tmp/Rtmpror1TN/unrtf
── Sitrep ──────────────────────────────────────────────────────────────────────
✔ URLs ok.
✖ Favicons not ok.
  Package logo is newer than favicons.
  Do you need to rerun `build_favicons()`?
✔ Open graph metadata ok.
✔ Articles metadata ok.
✔ Reference metadata ok.
```

**Comment by maelle** [comment]
Regarding the search box disappearance, it's due to a fix in pkgdown https://github.com/r-lib/pkgdown/blob/main/NEWS.md#_pkgdownyaml

> You can now choose where the search box is placed with the "search" navbar component. This has been documented for a very long time, but as far as I can tell, never worked (#2320). If you have made your own template with a custom navbar, you will need to remove the <form> with role="search" to avoid getting two search boxes.

The fix has to happen on the side of the packages as in https://github.com/ropensci/magick/pull/401, unless we want to add some sort of compatibility layer within rotemplate.

**Comment by maelle** [comment]
https://github.com/ropensci/mctq/pull/33

**Comment by maelle** [comment]
https://github.com/ropensci/jagstargets/pull/33

**Comment by maelle** [comment]
reg https://docs.ropensci.org/dynamite/articles/dynamite_priors.html has math always been this ugly? it looks a tad off

**Comment by maelle** [comment]
https://github.com/ropensci/drake/pull/1376

**Comment by maelle** [comment]
https://github.com/ropensci/MtreeRing/pull/16

**Comment by maelle** [comment]
https://github.com/ropensci/jstor/pull/90

**Comment by maelle** [comment]
https://github.com/ropensci/osfr/commit/67315ad3cff5d153e21d462f554f877ff8d5bcd3 (committed to the default branch as the latest commit was two years ago)

**Comment by maelle** [comment]
https://github.com/ropensci/spiro/pull/11

**Comment by maelle** [comment]
https://github.com/ropensci/codemetar/commit/f05d72aeae75682a3c88ff976311fcfe118df29d

**Comment by maelle** [comment]
https://github.com/ropensci/spatsoc/pull/63

**Comment by maelle** [comment]
https://github.com/ropensci/tic/pull/338

**Comment by maelle** [comment]
https://github.com/ropensci/NLMR/pull/109

**Comment by maelle** [comment]
https://github.com/ropensci/phruta/issues/22

**Comment by maelle** [comment]
https://github.com/ropensci/rfema/pull/14

**Comment by maelle** [comment]
https://github.com/ropensci/terrainr/pull/71

**Comment by maelle** [comment]
TODO 

- https://github.com/ropensci/workloopR/blob/d2122c751ffcc1690cb482e7f01b50845fef382a/_pkgdown.yml#L12
- https://github.com/ropensci/stantargets/blob/9ffea0b03b8f8a6774b6e52d5bc8b181dcffe37b/_pkgdown.yml#L4
- https://github.com/ropensci/gittargets/blob/013ed97c88c78d466edf458b54bcdde95d5061a0/_pkgdown.yml#L4
- https://github.com/ropensci/mapscanner/blob/1a210ce77ad1b83a8baad29960d4c891e6b1fda8/_pkgdown.yml#L27
- https://github.com/ropensci/tsbox/blob/ad278e22cdc532043e83c938b5aca318e20d2efe/_pkgdown.yml#L105
- https://github.com/ropensci/tarchetypes/blob/dc552e9561721ea7d4f19154fd5aea5cce6bf54f/_pkgdown.yml#L4
- https://github.com/ropensci/patentsview/blob/101468a68b8937fd0f2943b4c864816784dd0b64/_pkgdown.yml#L27
- ...

**Comment by maelle** [comment]
not breaking anyway: https://github.com/ropensci/workloopR/pull/3

**Comment by maelle** [comment]
https://github.com/ropensci/stantargets/pull/66

**Comment by maelle** [comment]
https://github.com/ropensci/gittargets/pull/17

**Comment by maelle** [comment]
https://github.com/ropensci/mapscanner/pull/51

**Comment by maelle** [comment]
https://github.com/ropensci/tsbox/pull/225

**Comment by maelle** [comment]
https://github.com/ropensci/tarchetypes/pull/182

**Comment by maelle** [comment]
https://github.com/ropensci/patentsview/pull/34

**Comment by maelle** [comment]
https://github.com/ropensci/visdat/pull/168

**Comment by maelle** [comment]
https://github.com/ropensci/googleLanguageR/pull/88

**Comment by maelle** [comment]
https://github.com/ropensci/osmdata/pull/345

**Comment by maelle** [comment]
https://github.com/ropensci/mapscanner/pull/52

**Comment by maelle** [comment]
https://github.com/ropensci/git2rdata/pull/73

**Comment by maelle** [comment]
https://github.com/ropensci/dbparser/pull/171

**Comment by maelle** [comment]
https://github.com/ropensci/osmplotr/pull/67

**Comment by maelle** [comment]
https://github.com/ropensci/rdefra/pull/20

**Comment by maelle** [comment]
https://github.com/search?q=left+user%3Aropensci+path%3A**%2F_pkgdown.yml&type=code&ref=advsearch

**Comment by maelle** [comment]
https://github.com/ropensci/targets/pull/1303

**Comment by maelle** [comment]
https://github.com/ropensci/iheatmapr/pull/107

**Comment by maelle** [comment]
https://github.com/ropensci/nomisr/pull/34

**Comment by maelle** [comment]
https://github.com/ropensci/phylotaR/pull/72

**Comment by maelle** [comment]
https://github.com/ropensci/nlrx/pull/102

**Comment by maelle** [comment]
https://github.com/ropensci/eia/pull/24

**Comment by maelle** [comment]
https://github.com/CornellLabofOrnithology/auk/pull/82

**Comment by maelle** [comment]
https://github.com/ropensci/rdhs/pull/153

**Comment by maelle** [comment]
https://github.com/ropensci/tiler/pull/25

**Comment by maelle** [comment]
https://github.com/ropensci/epubr/pull/4

**Comment by maelle** [comment]
https://github.com/ropensci/EndoMineR/pull/89

**Comment by maelle** [comment]
https://github.com/ropensci/hddtools/pull/35

**Comment by maelle** [comment]
https://github.com/ropensci/iheatmapr/pull/109
