### ISSUE TITLE
bold

### ISSUE THREAD

**Issue by maelle** [ropensci-org/rotemplate#115]
https://github.com/ropensci/docs/issues/17

thanks @peterdesmet

**Comment by maelle** [comment]
I actually see the bold font for the deployed website, so that might be a problem with how the font is loaded.

![image](https://github.com/user-attachments/assets/59b78b81-8f08-47b8-bdf9-cf6900c2720d)

**Comment by maelle** [comment]
@peterdesmet do you see any error in the browser console?

**Comment by peterdesmet** [comment]
Oh, indeed, it looks ok in Safari, but not in Chrome (Mac `Version 14.5`, Chrome `Version 127.0.6533.120 (Official Build) (arm64)`). I notice one console error:

<img width="537" alt="Screenshot 2024-08-29 at 14 39 10" src="https://github.com/user-attachments/assets/e5738c62-5062-4747-80a0-6043b5fddbe4">

If I disable the `font-family` on `body` it works, the text is bold (in the default font)

<img width="385" alt="Screenshot 2024-08-29 at 14 40 04" src="https://github.com/user-attachments/assets/30136579-0e34-4ba9-a95f-c59224c29e13">

**Comment by maelle** [comment]
thank you! do you have the text for the error?

**Comment by peterdesmet** [comment]
I notice now the error is unrelated to the CSS error:

```
ReferenceError: CookieConsent is not defined
    at matomo.js:17:5
```

CSS inspection:
<img width="1093" alt="Screenshot 2024-08-29 at 14 45 52" src="https://github.com/user-attachments/assets/7165bc61-ad1a-4885-a526-8556857ee963">

**Comment by maelle** [comment]
@jeroen any idea what we could explore?

**Comment by jeroen** [comment]
There was an issue with the cookieconsent library cdn. That part should now be fixed, but I don't think that is related.

**Comment by jeroen** [comment]
I think we also need to include the bold variants of our proxima-nova fonts in our theme to support this: https://github.com/ropensci/roweb3/tree/main/themes/ropensci/static/fonts/proxima

Although I am personally of dropping the custom proxima-nova font and using the defaults, which look better and cause much less maintenance headaches.

**Comment by peterdesmet** [comment]
> Although I am personally of dropping the custom proxima-nova font and using the defaults, which look better and cause much less maintenance headaches.

+1 if this means having fonts like on [default pkgdown](https://pkgdown.r-lib.org/) sites

**Comment by jeroen** [comment]
Going to redeploy all sites to see if there are any unexpected issues.

**Comment by peterdesmet** [comment]
Thanks, resolved for for https://docs.ropensci.org/frictionless/articles/data-package.html#write

For housekeeping, https://github.com/ropensci-archive/docs/issues/17 can be closed too (but the repo is archived)

**Comment by maelle** [comment]
Thank _you_!
