### ISSUE TITLE
articles size

### ISSUE THREAD

**Issue by maelle** [ropensci-org/rotemplate#116]
https://github.com/ropensci/docs/issues/16

thanks @peterdesmet

**Comment by maelle** [comment]
See #117

**Comment by peterdesmet** [comment]
Thanks, resolved for for https://docs.ropensci.org/frictionless/ 🎉 

For housekeeping, https://github.com/ropensci-archive/docs/issues/16 can be closed too (but the repo is archived)

**Comment by maelle** [comment]
Thanks so much for reporting :pray:
