### ISSUE TITLE
CoC and Contributing links?

### ISSUE THREAD

**Issue by elinw** [ropensci-org/rotemplate#12]
I've experimented with pkgdown before and one thing I noticed is that CoC and Contributing links are not automatically added.    Would you think about that in an ROpenSci template?    Also (cough).

**Comment by maelle** [comment]
What do you mean by adding the links automatically?

There are functions for adding the contributing guide in github.com/ropenscilabs/rodev (WIP).

**Comment by elinw** [comment]
Okay I didn't see them.

**Comment by maelle** [comment]
no problem, was that what you were looking for?

You'll be forgiven for not seeing functions we have not promoted yet :wink: Any feedback welcome!

**Comment by maelle** [comment]
@elinw is https://ropenscilabs.github.io/rodev/reference/use_ro_github.html what you were looking for?

**Comment by Rekyt** [comment]
@elinw were you thinking of having a direct link to CoC and Contributing links in the sidebar in the "Links" section?

**Comment by maelle** [comment]
@elinw friendly ping :smile_cat:

**Comment by elinw** [comment]
What I ended up doing is adding an Etc menu item
https://ropensci.github.io/skimr/

By adding to the yml.
https://github.com/ropensci/skimr/blob/master/_pkgdown.yml

**Comment by maelle** [comment]
I see, @noamross did something similar for https://noamross.github.io/redoc/

Elin, are you suggesting making this part of the template/a builder function for all repos that do have a contributing guide + COC? (all onboarded packages should, but not all packages have been peer-reviewed).

**Comment by elinw** [comment]
Yes, I think it would be really good to incorporate them into the template (when available).

**Comment by maelle** [comment]
Ok, good suggestion, I asked in pkgdown repo https://github.com/r-lib/pkgdown/issues/1044, if not an accepted feature request there we could add that to our build pipeline I guess.

**Comment by maelle** [comment]
@elinw this has been solved in pkgdown dev version (i.e. I made a PR implementing your idea) that is used by the rOpenSci central docs building https://ropensci.org/technotes/2019/06/07/ropensci-docs/ so after your next commit if I understand correctly you should see "community files" in the sidebar. I'll add an emoji for that sidebar section in rotrmplate before closing the issue 😉

**Comment by maelle** [comment]
@jeroen does the docs building system use pkgdown dev version?
