### ISSUE TITLE
increase contrast

### ISSUE THREAD

**Issue by maelle** [ropensci-org/rotemplate#14]
cf https://github.com/ropensci/dev_guide/issues/138#issuecomment-485804011

**Comment by maelle** [comment]
- [x] Done for links

- [ ] Decision to be made regarding the navbar

- [x] For comments in code chunks what's applied now is the `pkgdown` default cf https://github.com/r-lib/pkgdown/issues/1003 -- fixed in ropensci.css

**Comment by jeroen** [comment]
We talked about this at the all-hands meeting, and agreed things are ok for now. Contrast is just one of the hundreds of accessibility details of a website. We're not expects at this, but to my best judgement the website is very readable now.

**Comment by maelle** [comment]
and when/if we overhaul the main website, we'll remember to update the template.
