### ISSUE TITLE
navbar covers content on page on small screens

### ISSUE THREAD

**Issue by dpprdan** [ropensci-org/rotemplate#15]
When viewed on small screens, the navbar covers the content of the page, like here (Firefox on a Moto G5 plus with Full HD screen):

![grafik](https://user-images.githubusercontent.com/1423562/57215386-fed75280-6fec-11e9-85bd-590b0a43e650.png)

This is equivalent to https://github.com/tidyverse/tidytemplate/issues/42

**Comment by maelle** [comment]
Thanks! This is not optimal indeed. I'll wait a bit before handling this, in the hope `tidytemplate` solves it before then :grin:

**Comment by maelle** [comment]
@dpprdan does the new navbar design by @jeroen solve your display issue? See https://ropensci.github.io/rotemplate/

**Comment by dpprdan** [comment]
Unfortunately not:

![grafik](https://user-images.githubusercontent.com/1423562/57286549-bc2d7d00-70b5-11e9-875d-09f9616a295f.png)

BTW Firefox (on Desktop) has a [Responsive Design Mode](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode) which makes it easier to test this (Ctrl + Shift + M (or Cmd + Opt + M on macOS)). My phone seems to be similar to the Galaxy S9 preset.

**Comment by jeroen** [comment]
Looks like the title font is just too large. I'll make it smaller.

**Comment by maelle** [comment]
Thanks @dpprdan for the bug report and @jeroen for the fix! :tada:

**Comment by dpprdan** [comment]
Unfortunately I now see
![rotemplate_2019-05-26](https://user-images.githubusercontent.com/1423562/58386114-63d60500-7ffb-11e9-88d2-ca3579b62972.png)

A quick fix might be to hide the version number https://github.com/tidyverse/tidytemplate/issues/42#issuecomment-495992752.

A safer fall-back for long package names would require some javascript/css tweaks which might be incorporated in pkgdown https://github.com/r-lib/pkgdown/pull/1041.

**Comment by jeroen** [comment]
Did you refresh the page? I see this:

**Comment by jeroen** [comment]
Did you refresh the page? I see this:

![Screenshot_20190526-230204](https://user-images.githubusercontent.com/216319/58396026-3022cb80-804b-11e9-8284-b9c90636bb56.png)

**Comment by dpprdan** [comment]
@jeroen Yes, your screen is just wider (~an iPhone Plus/Max model?~ eh, that's Chrome on Android of course). See the first line of the body "rotemplate provides a custom ~pkgdown~". 
My last screenshot is actually via Firefox RDM (Galaxy S9 preset, but see also the presets for smaller iPhones) but it looks the same on my mobile with both Firefox and Chrome.

**Comment by jeroen** [comment]
In this case both the name of the package and the version are very long, so hopefully most packages won't be affected by this. 

I can't really test this on your phone, but on my browser it looks OK if the display width is at least 400px (which seems most common these days). I added a small css tweak that should hopefully result in better display if the device is smaller than that.

**Comment by dpprdan** [comment]
Close enough. 🎉 

![grafik](https://user-images.githubusercontent.com/1423562/58409179-d1bc1400-806f-11e9-9779-612285bd82be.png)

> 400px (which seems most common these days)

360px width still [seems to be a quite popular viewport](https://deviceatlas.com/blog/viewport-resolution-diagonal-screen-size-and-dpi-most-popular-smartphones#iphones) on Android devices (Samsung, Motorola, LG, Huawei) and 375px on iPhones.

**Comment by jeroen** [comment]
Right close enough :) Maybe I'll decrease the left margin on the title a bit more.

Most packages won't suffer from this anyway because they don't carry such long version numbers. For example https://docs.ropensci.org/opencage/ seems fine.

**Comment by jeroen** [comment]
Can you refresh and check one final time? There should now be a little less margin between the ropensci logo and the title of the package.

**Comment by maelle** [comment]
> Most packages won't suffer from this anyway because they don't carry such long version numbers.

Well I hope we'll encourage dev version numbers like this, in particular for the dev website (see https://github.com/ropensci/docs/issues/5)

**Comment by dpprdan** [comment]
@jeroen:
 
![grafik](https://user-images.githubusercontent.com/1423562/58415216-0b941700-807e-11e9-85e9-1023c83a968c.png)

You can also check with Firefox [Responsive Design Mode](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode) or Chrome [DevTools Device Mode](https://developers.google.com/web/tools/chrome-devtools/device-mode/). They are not 100% accurate but, well, close enough. 😉
