### ISSUE TITLE
Add Google Analytics tracker

### ISSUE THREAD

**Issue by jeroen** [ropensci-org/rotemplate#17]
All all hands we discussed it would be nice to see which pkgdown sites and which pages are visited most.

**Comment by maelle** [comment]
we should keep https://github.com/r-lib/pkgdown/issues/1009 in mind when doing so.

**Comment by jeroen** [comment]
I don't think that collecting website statistics is violates privacy. Almost any website in the world does this. We're not requesting or storing any personal information.

**Comment by maelle** [comment]
No I understood that we do need to inform the website visitors. I need to read stuff before closing.

**Comment by jeroen** [comment]
I highly doubt this, every website in the world collects statistics. I don't think it's worth spending a lot of time on this, but if you want to do more research, go for it.
