### ISSUE TITLE
images broken if using relative urls

### ISSUE THREAD

**Issue by robbriers** [ropensci-org/rotemplate#19]
If relative URLS are used to link to images in README.md or index.md then they are broken when rendered to docs.ropensci.org

example: https://docs.ropensci.org/tidyhydat/

**Comment by jeroen** [comment]
🤔 Is this a bug in the template? Does does not happen for pkgdown with the standard template?

**Comment by hadley** [comment]
pkgdown only supports images in a few locations since only a few locations also work with CRAN's rendering of readmes. `tools/` is not one of those locations. Use `man/figures` for images.

**Comment by jeroen** [comment]
@robbriers can you try moving your images to `man/figures` and see if that fixes your docs?
