### ISSUE TITLE
Adapt special theme for ropenscilabs

### ISSUE THREAD

**Issue by jeroen** [ropensci-org/rotemplate#20]
In our staff meeting on July 31 we discussed again the question if we should build and host docs for unsupported and silly ropenscilabs packages.

We decided we want to keep providing docs for everything in the registry, but display labs package with a an adapted theme that emphasizes this is not an official on-boarded ropensci project, but rather an experimental package.

**Comment by maelle** [comment]
What remains to be done here? Would you like a different theme that what's currently the case for ropenscilabs websites?

**Comment by jeroen** [comment]
No I think what we have now is fine for now. I decided to do some tweaking of the template betty. We don't even have consensus if we want to keep providing docs for labs pkgs, so no point investing in a second template.
