### ISSUE TITLE
Add twitter / facebook thumbnail

### ISSUE THREAD

**Issue by jeroen** [ropensci-org/rotemplate#21]
Test with https://cards-dev.twitter.com/validator

**Comment by maelle** [comment]
Yesss. For that you'd need to inject a logo.png, and while you're at it, a favicons folder if it doesn't exist. This very repo has both the logo and favicons files, and it has a nice Twitter card.

**Comment by jeroen** [comment]
The favicon's are not part of the template because they are part of the root [docs.opensci.org](https://github.com/ropensci-docs/ropensci-docs.github.io) site. See they work:  https://docs.ropensci.org/favicon.ico

**Comment by maelle** [comment]
Ok. Regarding the Twitter / OG image maybe we should wait until https://github.com/r-lib/pkgdown/pull/1143 has been merged (I hope the feature will be accepted) this way you could have an OG image stored at docs.ropensci.org too.

**Comment by maelle** [comment]
@jeroen https://pkgdown.r-lib.org/articles/metadata.html#site-wide-customization

rgbif has a nice card, magick does not.
