### ISSUE TITLE
Customize 404 page

### ISSUE THREAD

**Issue by jeroen** [ropensci-org/rotemplate#22]
We can add a `404.md` somewhere to get a better `404.html` page, similar to: https://docs.ropensci.org/doesnotexist

Currently we get something standard like: https://docs.ropensci.org/antiword/doesnotexist

**Comment by maelle** [comment]
But we'd still want the pkgdown 404 of a package to have the navbar etc. of that package?

pkgdown uses .github/404.md, if present, for the content of the 404.

**Comment by maelle** [comment]
Would the 404.md be injected if it doesn't exist?

```Markdown
# Oh no! It's a 404!

The page you are looking for cannot be found.

![rOpenSci friendly bot](https://docs.ropensci.org/ropenscibot.png)
```

**Comment by maelle** [comment]
I.e. I don't think it can happen via the template package?

**Comment by jeroen** [comment]
I thought this was something that could be templated as well. Maybe it's not.

**Comment by maelle** [comment]
@jeroen well it could still be injected when building the package if .github/404.md does not exist?

**Comment by maelle** [comment]
I find the default ok https://docs.ropensci.org/mctq/bla
