### ISSUE TITLE
Filename of package logo

### ISSUE THREAD

**Issue by KevCaz** [ropensci-org/rotemplate#23]
Hi there, 

I guess this issue is related to how pkgdown websites are deployed on https://docs.ropensci.org.

It looks like the filename of the logo matters,  using `rcites_logo.png` I still have my logo but also the RopenSci one, see the difference between https://docs.ropensci.org/rcites/ and https://ropensci.github.io/rcites/.

I guess this is just a matter of adding a sentence (or a link) in the readme mentioning what the logo filename should be! 

Hope this helps and thanks for your work on this!

**Comment by jeroen** [comment]
Can you move the logo `<img>` from your readme inside the h1 title? so like this:

```md
# rcites <img src="man/figures/rcites_logo.png" width="130" height="150" align="right"/>
```

**Comment by KevCaz** [comment]
Done! It worked https://docs.ropensci.org/rcites/ :+1: .
Do you want me to close this issue?

**Comment by jeroen** [comment]
Great thanks!
