### ISSUE TITLE
Make sure we remove type inverse

### ISSUE THREAD

**Issue by maelle** [ropensci-org/rotemplate#28]
https://github.com/ropensci/citesdb/blob/ca579791a574b04e04c755c569a916a838db2ef8/pkgdown/_pkgdown.yml#L6

**Comment by maelle** [comment]
Shouldn't this happen in betty @jeroen?

**Comment by maelle** [comment]
i.e. in https://github.com/jeroen/betty/blob/3c0a78c76cf1e97c9bc9ac31d67567d0f773bcb8/R/build.R#L71

that said I'm not sure yet what the type value would be (NULL, NA...), I'll need to try that.

**Comment by jeroen** [comment]
I think our template should work with any config and ignore parameters that are not supported. But perhaps this is setting is hardcoded in pkgdown?

If nothing else perhaps we can indeed add it to the `overrides` in betty. But it would be much better if we don't need to override things.

**Comment by maelle** [comment]
oh actually we can just edit https://github.com/ropensci/rotemplate/blob/9a4f4767f785dccb2adde74b3ce14ebd3b17957b/inst/pkgdown/templates/navbar.html#L2

**Comment by maelle** [comment]
will do tomorrow unless you do it earlier.

**Comment by jeroen** [comment]
I'll do it now :)

**Comment by maelle** [comment]
I should probably also look at other such parameters there are in the templates. Or you should do that ;-)
