### ISSUE TITLE
add schema.org terms to template?

### ISSUE THREAD

**Issue by maelle** [ropensci-org/rotemplate#30]
cf https://github.com/ropensci/codemetar/issues/192#issuecomment-557204590

cc @cboettig

**Comment by cboettig** [comment]
can you remind me which template?  really the only  thing this needs I think is swapping out the value of the `@context` element, since the terms should be consistent..

**Comment by maelle** [comment]
I suppose we need to edit https://github.com/ropensci/rotemplate/blob/master/inst/pkgdown/templates/head.html? with something like "schema.org blabla {{{ pkgname }}} blabla" and then things such as pkgname need to be passed (I'm unsure we can make it work from here as opposed to from pkgdown or a pkgdown wrapper, but fingers crossed, I'll have a look next week).

What website head could I use as a model? GitHub repos are software sources not software docs, do you know software docs websites with good schema.org terms embedded?

**Comment by cboettig** [comment]
ah, good question!  there's no need to embed it in a `head` in `meta` or rdf elements, one can embed the json-ld directly inside a `<script type="application/ld+json">` block (which can be anywhere in the doc, often in the footer).  

For a nice example of a site that does this, see Zenodo's software pages, e.g. after the footer at line 598 for codemetar record: 

view-source:https://zenodo.org/record/2648599#.XdbpMZNKgWo

(yes, it seems ironic that Zenodo already knows how to convert (some of) it's internal format into schema.org / codemeta, it just doesn't know how to take codemeta as input; instead requiring it's native `.zenodo.json` schema or guessing based on crosswalking metadata from the GitHub API ....)
