### ISSUE TITLE
Weird navbar

### ISSUE THREAD

**Issue by maelle** [ropensci-org/rotemplate#31]
Not sure why yet @jeroen

https://docs.ropensci.org/grainchanger/

**Comment by maelle** [comment]
![Screenshot_20191129-205247](https://user-images.githubusercontent.com/8360597/69888092-61c26b00-12ea-11ea-8469-d38a7ae3e529.jpg)

On my tablet.

**Comment by maelle** [comment]
I am guessing I get that for this site because the package name is long.

**Comment by jeroen** [comment]
Looks OK on my laptop and phone...
