### ISSUE TITLE
Serve resources common to all websites from the same URL

### ISSUE THREAD

**Issue by Bisaloo** [ropensci-org/rotemplate#36]
It would be great if resources shared between all rOpenSci pkgdown websites (e.g. `hexlogo.png`, `ropensci.css`, `link.svg`, `pkgdown.css`, `pkgdown.js`) could be served from the same URL. For example:

https://docs.ropensci.org/ropensci.css instead of https://docs.ropensci.org/PACKAGE/ropensci.css

(in the code `<link href="../ropensci.css" rel="stylesheet">` instead of `<link href="ropensci.css" rel="stylesheet">`).

This would enable caching across all rOpenSci pkgdown websites, thereby increasing speed, and decreasing bandwidth usage.

**Comment by jeroen** [comment]
We could do it for the logo, but I don't think for the css/js files. The reason pkgdown deploys the css/js files with the page instead of serving them from some cdn, is that these files can change for each version.

Serving everything from a single place would make it really hard to make changes to our template, because we would need to update the css file and all package sites at the same time.

**Comment by maelle** [comment]
@jeroen what do you mean reg the logo? At the moment, if the authors don't add a logo themselves, no logo is used?

In the dev guide I'd like to recommend authors to generate the logo file if their package has a logo, but what should we recommend to authors whose package doesn't have a logo?

cf https://github.com/ropensci/dev_guide/issues/217

**Comment by maelle** [comment]
:wave: @jeroen :smile_cat:

**Comment by jeroen** [comment]
I mean the ropensci logo image in the navbar and footer. This is the same for each package.

What do you mean by a package logo? The hex in the title?

**Comment by maelle** [comment]
ah ok, so the two issues aren't related.

Yes I think you once mentioned something about improving the guidance for package logos, is the problem just that some people don't know where to put it for pkgdown to find it?

**Comment by jeroen** [comment]
There are countless examples of people using a custom hex logo: 

 - https://docs.ropensci.org/drake/
 - https://docs.ropensci.org/eia/
 - https://docs.ropensci.org/rgbif/

So you can look at those examples, I think `man/figures` is the recommended place for such figures. Maybe the guidance can just state to look at other packages :)

Packages that do not have a custom logo in the title, get the default ropensci logo, which is also fine: 

 - https://docs.ropensci.org/magick/
 - https://docs.ropensci.org/tesseract
 - https://docs.ropensci.org/av

**Comment by maelle** [comment]
ah ok I didn't know that second part, thanks.

should we close this issue?
