### ISSUE TITLE
Top navbar shadow remains even after top navbar has been hidden

### ISSUE THREAD

**Issue by Bisaloo** [ropensci-org/rotemplate#37]
Step to reproduce:

- Visit e.g. https://docs.ropensci.org/lightr/
- Scroll down until top navbar disappears (because of `headroom.js`)
- Notice how the navbar shadow is still here

This sounds like a bug to me. The shadow should vanish once the element it comes from isn't here anymore.

**Comment by jeroen** [comment]
I don't know I think it looks nice actually :) Does it really bother you?

**Comment by Bisaloo** [comment]
No, I wouldn't say it bothers me :smile: since it's not hampering the functionality. I do think it looks kind of strange, it's really uncommon for webpages to have this shadow out of nowhere at the top of the page, but not enough to argue if you like it.

**Comment by jeroen** [comment]
Well it's not out of nowhere, it's there from the navbar (even if the navbar itself is out of sight) ;)

Inner shadows are not entirely uncommon, let's call it an aesthetic choice from the artist.
