### ISSUE TITLE
ToC broken with pkgdown v1.5.0

### ISSUE THREAD

**Issue by pat-s** [ropensci-org/rotemplate#38]
{pkgdow} now uses [bootstrap-toc](https://afeld.github.io/bootstrap-toc/) plugin for the ToC sidebar in [articles](https://pkgdown.r-lib.org/news/index.html#new-features).
This breaks all ToC of packages using {rotemplate}. [Example: tic](https://docs.ropensci.org/tic/articles/deployment.html)

See the [PR diff](https://github.com/r-lib/pkgdown/pull/1257/files) for changes.

Also this commit in [mlr3pkgdowntemplate](https://github.com/mlr-org/mlr3pkgdowntemplate/commit/81afe9aced657997563ccea2c2970219e5452aa4) might be helpful to get it fixed quickly.

**Comment by jeroen** [comment]
Ugh why do they keep doing this 🙈 . Thanks for the report!

**Comment by jeroen** [comment]
I think I have solved the immediate problem. Going to deploy now on the build servers... should be live after an hour.

Let me know if you find other problems ! Thanks again.
