### ISSUE TITLE
Fix horizontal scroll

### ISSUE THREAD

**Issue by jeroen** [ropensci-org/rotemplate#40]
If there is a vertical scrollbar, we also get horizontal scroll :(

I'm sure it wasn't there before.

**Comment by maelle** [comment]
Any example URL?

**Comment by Bisaloo** [comment]
I get this on https://docs.ropensci.org/lightr/ for example

**Comment by Bisaloo** [comment]
The issue seems to be somewhere here:

https://github.com/ropensci/rotemplate/blob/4d90b210ff65b1b1854cc034aff64bc4b1788ef9/inst/pkgdown/assets/ropensci.css#L154-L166

It goes away if you edit these lines.

The issue is that `vw` doesn't take into account the space used by the scrollbar. So when there is one, content overflows.

**Comment by jeroen** [comment]
That code was working fine before though; I don't understand what has changed in the past few weeks.

**Comment by jeroen** [comment]
I guess we can add

```css
html{
  overflow-x: hidden;
}
```

But that just hides the scroll bar, it doesn't prevent the overflow.

**Comment by maelle** [comment]
Is the problem specific to rotemplate btw?

**Comment by Bisaloo** [comment]
Well, it's not the case in the default pkgdown style if that's what you mean. Now, it's possible other orgs have had the same issue.

**Comment by jeroen** [comment]
I've added a workaround to hide the horizontal scrollbar now, but I'd like to revisit this at some point to see if there is a way to properly prevent the overflow.

The problem is indeed the footer from our template. I'm setting it to `width: 100vw` to force it to full width, even though pkgdown puts the footer inside a fixed width container.

**Comment by maelle** [comment]
Should we revisit after the main website redesign (that might change the footer)?
