### ISSUE TITLE
pkgdown GH build states: "rotemplate is not installed"

### ISSUE THREAD

**Issue by njtierney** [ropensci-org/rotemplate#49]
Hi there!

When my [visdat](https://github.com/ropensci/visdat) package is being built I get this error on GH actions.

```
== Building pkgdown site =======================================================
Reading from: '/Users/runner/work/visdat/visdat'
Writing to:   '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmps0XlXh/file816547b99c9'
-- Initialising site -----------------------------------------------------------
Copying '../../_temp/Library/pkgdown/assets/bootstrap-toc.css' to 'bootstrap-toc.css'
Copying '../../_temp/Library/pkgdown/assets/bootstrap-toc.js' to 'bootstrap-toc.js'
Copying '../../_temp/Library/pkgdown/assets/docsearch.css' to 'docsearch.css'
Copying '../../_temp/Library/pkgdown/assets/docsearch.js' to 'docsearch.js'
Copying '../../_temp/Library/pkgdown/assets/link.svg' to 'link.svg'
Copying '../../_temp/Library/pkgdown/assets/pkgdown.css' to 'pkgdown.css'
Copying '../../_temp/Library/pkgdown/assets/pkgdown.js' to 'pkgdown.js'
Error: Error: rotemplate is not installed
11 Removing worktree 11111111111111111111111111111111111111111111111111111111111
Running git worktree remove \
  /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmps0XlXh/file816547b99c9
Execution halted
Error: Process completed with exit code 1.
```

https://github.com/ropensci/visdat/runs/3187831393

I'm not sure that I've changed anything in my [pkgdown YAML](https://github.com/ropensci/visdat/blob/master/.github/workflows/pkgdown.yaml) to trigger this - but looking at the [pkgdown for magick](https://github.com/ropensci/magick/blob/master/_pkgdown.yml) and their [github workflows](https://github.com/ropensci/magick/tree/master/.github/workflows) - perhaps I don't actually need this pkgdown YAML or GH action?

**Comment by maelle** [comment]
:wave: @njtierney! I think you can indeed remove this workflow indeed as your website is built on [rOpenSci docs server](https://ropensci.org/blog/2019/06/07/ropensci-docs/) (built and maintained by @jeroen) -- fun fact, the URL to visdat website is even one of the examples in that blog post.

If you _want_ to build your pkgdown website for e.g. PR previews (deployed via e.g. Netlify) you can and you could either
* remove the line indicating rotemplate is to be used. https://github.com/ropensci/visdat/blob/4170c36765873e37ef3a6e38029b7083eb355620/_pkgdown.yml#L4
* make sure your workflow is installing rotemplate.

Note that you could also remove the docsearch API parameters from your pkgdown configuration as @jeroen set up Algolia search for all sites so the parameters are overriden (unless you set up a preview workflow as explained earlier).

**Comment by njtierney** [comment]
Hi @maelle !

OK great, it looks like that worked, however I am still having this other issue I was encountering, where my website doesn't work anymore?

http://visdat.njtierney.com/

I'm not sure if this is because I need to update some part of the CNAME record - I have just changed this to `ropensci.github.io` instead of `njtierney.github.io`.

![image](https://user-images.githubusercontent.com/6488485/128464663-09349619-7e7c-446c-ace8-eb4554a207dc.png)

Apologies that this is a bit off topic for this problem, happy to close this issue :)

**Comment by maelle** [comment]
:thinking: Everything I know about redirects should be in https://devguide.ropensci.org/redirect.html

**Comment by jeroen** [comment]
Hi @njtierney, you indeed don't need any pkgdown github action, I would recommend removing it indeed. The docs on https://docs.ropensci.org/visdat/ are automatically built for all ropensci packages, e.g. https://dev.ropensci.org/job/visdat

The site ropensci.github.io/visdat now redirects to docs.ropensci.org/visdat (and I think your homepage mirrors the former?)
