### ISSUE TITLE
Search field from rotemplate is not working

### ISSUE THREAD

**Issue by danielvartan** [ropensci-org/rotemplate#50]
Hi,

I recently moved my package to rOpenSci. All things worked as described, but the search field of the package documentation website simply doesn't work. Is there something I miss?

The package documentation website can be found at https://docs.ropensci.org/mctq/ .

Cheers!

**Comment by jeroen** [comment]
Hi! This field depends on an external service from algolia to index the pkgdown site. Sometimes it takes them a while to scrape the docs and discover that there is a new package. Let's give it some more time :)

@maelle is the new pkgdown using another search mechanism?

**Comment by maelle** [comment]
Yes the new pkgdown uses local search! :grin:

**Comment by maelle** [comment]
But local search is with BS5 so we'll need a bit of work here.

**Comment by maelle** [comment]
@jeroen how much time does it usually take? Does one need to re-trigger a website build?

**Comment by jeroen** [comment]
I don't think there is anything we can do. It is like search engine, such as google, you can't control when they crawl your site. I do look forward to switching to local search that does not depend on another party.

**Comment by danielvartan** [comment]
Is there a way to remove the search field?

**Comment by jeroen** [comment]
Maelle is working on a new template in https://github.com/ropensci-org/rotemplate/pull/52. This should be done soon-ish and resolve the issues.

**Comment by jeroen** [comment]
@danielvartan we are now testing the new template. Could you try if everything now seems OK? https://docs.ropensci.org/mctq/

**Comment by danielvartan** [comment]
Much better! Thanks @jeroen and @maelle for all your work and attention.

![image](https://user-images.githubusercontent.com/29462472/145623236-b71ee46b-2179-4f4b-902f-9487dfb925a0.png)
