### ISSUE TITLE
Check failed ropensci docs

### ISSUE THREAD

**Issue by jeroen** [ropensci-org/rotemplate#58]
See the docs column in https://ropensci.r-universe.dev/

Most problems are probably pre-existent, and not due to the new pkgdown. Still this may be a good moment to try and fix them, otherwise they won't get new docs. Maybe retire some things that are broken and unmaintained.

**Comment by maelle** [comment]
I'll handle the opengraph stuff from our wrapper.

**Comment by maelle** [comment]
https://github.com/ropensci/parzer/pull/37

**Comment by maelle** [comment]
https://github.com/ropensci/nomisr/pull/28

**Comment by maelle** [comment]
https://github.com/ropensci/rdataretriever/pull/292

**Comment by ethanwhite** [comment]
Just merged your fix for rdataretriever. Thanks!

**Comment by maelle** [comment]
https://github.com/ropensci/NLMR/pull/85

**Comment by maelle** [comment]
https://github.com/ropensci/taxadb/pull/99/

**Comment by maelle** [comment]
https://github.com/ropensci/rdataretriever/issues/293

**Comment by maelle** [comment]
https://github.com/ropensci-review-tools/autotest/pull/72

**Comment by maelle** [comment]
https://github.com/ropensci/biomartr/pull/78

**Comment by maelle** [comment]
https://github.com/ropensci/jsonvalidate/pull/56

**Comment by maelle** [comment]
https://github.com/ropensci/virtuoso/issues/39

**Comment by maelle** [comment]
https://github.com/ropensci/tidyhydat/pull/168

**Comment by maelle** [comment]
https://github.com/ropensci/nlrx/issues/59

**Comment by maelle** [comment]
https://github.com/ropensci/rppo/issues/8

**Comment by maelle** [comment]
https://github.com/ropensci/MODISTools/pull/37

**Comment by maelle** [comment]
https://github.com/ropensci/rdhs/pull/126

**Comment by maelle** [comment]
https://github.com/r-lib/pkgdown/pull/1967

**Comment by maelle** [comment]
https://github.com/ropensci/cyphr/pull/49

**Comment by maelle** [comment]
https://github.com/ropensci/wateRinfo/issues/92

**Comment by maelle** [comment]
https://github.com/ropensci/refsplitr/issues/83

**Comment by maelle** [comment]
Not a failure but still important IMO https://github.com/ropensci/biomartr/pull/79

**Comment by maelle** [comment]
https://github.com/ropensci/tidyhydat/pull/169

**Comment by maelle** [comment]
https://github.com/ropensci/MODISTools/pull/39

**Comment by maelle** [comment]
I do not understand hydroscoper error https://github.com/r-universe/ropensci/runs/4511975534?check_suite_focus=true

**Comment by maelle** [comment]
https://github.com/ropensci/prism/issues/107

**Comment by maelle** [comment]
https://github.com/ropensci/DataPackageR/pull/96

**Comment by maelle** [comment]
https://github.com/ropensci/essurvey/pull/54

**Comment by maelle** [comment]
https://github.com/ropensci/MODIStsp/pull/248

**Comment by maelle** [comment]
For reference https://github.com/r-lib/pkgdown/pull/1971

**Comment by maelle** [comment]
https://github.com/ropensci/MODIStsp/pull/250

**Comment by maelle** [comment]
https://github.com/ropensci/MODIStsp/pull/247

**Comment by maelle** [comment]
https://github.com/ropensci/MODIStsp/pull/249

**Comment by maelle** [comment]
https://github.com/ropensci/nbaR/issues/61

**Comment by maelle** [comment]
https://github.com/ropensci/nbaR/pull/62

**Comment by maelle** [comment]
https://github.com/ropensci/nbaR/issues/63

**Comment by maelle** [comment]
https://github.com/ropensci/rplos/commit/acb119b60d2b879ff377d943f38f04dcf0d9b1ed

**Comment by maelle** [comment]
https://github.com/ropensci/smapr/issues/70

**Comment by maelle** [comment]
https://github.com/ropensci/citesdb/issues/12

**Comment by maelle** [comment]
https://github.com/ropensci/geojsonio/pull/176

**Comment by maelle** [comment]
rbison seems to be a false positive as I can build the site locally https://github.com/r-universe/ropensci/runs/4556548470?check_suite_focus=true However I can't trigger a new build.

**Comment by maelle** [comment]
https://github.com/ropensci/Rclean/pull/211

**Comment by maelle** [comment]
https://github.com/ropensci/rAltmetric/commit/81e8790115219c5852c6ed34d6a4d0474e493d39

**Comment by maelle** [comment]
https://github.com/ropensci/infx/issues/11

**Comment by maelle** [comment]
https://github.com/ropensci/infx/issues/12

**Comment by maelle** [comment]
https://github.com/ropensci/refimpact/pull/31

**Comment by maelle** [comment]
https://github.com/ropensci/popler/issues/64

**Comment by maelle** [comment]
https://github.com/ropensci/popler/issues/65

**Comment by maelle** [comment]
https://github.com/ropensci/rdopa/issues/27

**Comment by maelle** [comment]
https://github.com/ropensci/IEEER/issues/19

**Comment by maelle** [comment]
https://github.com/ropensci/NLMR/pull/87

**Comment by jeroen** [comment]
> rbison seems to be a false positive as I can build the site locally https://github.com/r-universe/ropensci/runs/4556548470?check_suite_focus=true However I can't trigger a new build.

I tried a rebuild, but it keeps giving http 500 server errors for me, also locally.

**Comment by maelle** [comment]
https://github.com/ropensci/rbison/issues/70

**Comment by maelle** [comment]
https://github.com/ropensci/NLMR/issues/88

**Comment by maelle** [comment]
https://github.com/ropensci/NLMR/pull/89

**Comment by maelle** [comment]
https://github.com/ropensci/codemetar/issues/329

**Comment by maelle** [comment]
https://github.com/ropensci/SymbiotaR2/pull/10

**Comment by maelle** [comment]
https://github.com/ropensci/jaod/issues/13

**Comment by maelle** [comment]
https://github.com/ropensci/NLMR/issues/91

**Comment by maelle** [comment]
I sent a few emails / DMs. :eyes:

**Comment by maelle** [comment]
https://github.com/ropensci/tidytags/issues/60

**Comment by maelle** [comment]
https://github.com/ropensci/stplanr/issues/480

**Comment by maelle** [comment]
https://github.com/ropensci/tic/issues/311

**Comment by maelle** [comment]
https://github.com/ropensci/beastier/issues/62

**Comment by maelle** [comment]
https://github.com/ropensci/rrricanes/issues/126

**Comment by maelle** [comment]
Tracking unsolved issues in #91
