### ISSUE TITLE
Missing CRAN Release date

### ISSUE THREAD

**Issue by dieghernan** [ropensci-org/rotemplate#63]
Hi:

When having a look to my [CHANGELOG](https://docs.ropensci.org/cffr/news/index.html) on a smartphone  I can’t see the CRAN release date:

![825E8066-F98E-4DF0-880E-53BE0C19836A](https://user-images.githubusercontent.com/25656809/146065897-45894036-3fb4-4b4d-9f5c-cb31a567a8cb.png)

However copy-pasting I see that the element is there.

## cffr 0.1.1
CRAN release: 2021-11-11

A css issue?

**Comment by dieghernan** [comment]
So the issue is that the dates are:

```html
<p class="text-muted">CRAN release: 2021-12-03</p>

```

and the main template has:

https://github.com/ropensci-org/rotemplate/blob/90c8d030a2dc23caadea37a92e661dfffe1a6cae/inst/pkgdown/_pkgdown.yml#L17

**Comment by jeroen** [comment]
Thanks! Your site should now be fixed.

**Comment by dieghernan** [comment]
It is, thanks!
