### ISSUE TITLE
Not rendering math notations

### ISSUE THREAD

**Issue by danielvartan** [ropensci-org/rotemplate#67]
`rotemplate` is not rendering math notations. Possible issue with mathjax.

## Example:

* Source: https://docs.ropensci.org/mctq/reference/msl.html

![image](https://user-images.githubusercontent.com/29462472/148134909-6047397e-11a0-42e8-b18c-26a706dfcdb7.png)

**Comment by jeroen** [comment]
Our template [makes mathjax opt-in](https://github.com/ropensci-org/rotemplate/blob/master/R/build-site.R#L48-L60) because it is very heavy. Can you try adding `mathjax: true` to your `_pkgdown.yml`?

**Comment by jeroen** [comment]
Oh wait you already have this. Hmm then there is a bug.

**Comment by jeroen** [comment]
Actually fixed now 😄  Thank you for notifying us about the issue!
