### ISSUE TITLE
Header missing links on rtweet

### ISSUE THREAD

**Issue by llrs** [ropensci-org/rotemplate#74]
The other day I realized that on [rtweet](https://docs.ropensci.org/rtweet/) the buttons to reference, vignettes and articles are missing from the header. 

![Screenshot from 2022-01-14 12-50-59 of BaseSet](https://user-images.githubusercontent.com/6818218/149511206-3c38e979-15f7-4509-8b05-97adcbc80bf4.png)
![Screenshot from 2022-01-14 12-50-50 of rtweet](https://user-images.githubusercontent.com/6818218/149511210-4215fdf2-ecff-42ba-b4e6-48ee51d1ec03.png)

I think this is not a problem of building the website, but it might be related to other peculiarities of the package(?). 
Thanks for providing these templates!

**Comment by jeroen** [comment]
Maybe try to remove this:

https://github.com/ropensci/rtweet/blob/afccbffbda77a7ba9a64152fd2100e127c6210a1/_pkgdown.yml#L9-L12

**Comment by llrs** [comment]
I thought rOpenSci ignored that argument as it was there before the template, but now that I removed it, it works again. Thanks!

**Comment by maelle** [comment]
I think we'd let you re-write the whole navbar so we can't override it. :thinking: Opinions @jeroen?

**Comment by jeroen** [comment]
Yes I think it makes sense to leave the navbar content customizable by the pkg author.
