### ISSUE TITLE
pkgdown 2.0.2 broke our navbar

### ISSUE THREAD

**Issue by jeroen** [ropensci-org/rotemplate#76]
I think the update to pkgdown 2.0.2 broke our navbar. There is too much top-margin, and not enough bottom margin now. I think it has to do with our hexlogo in the nav bar. 
Probably related to https://github.com/r-lib/pkgdown/issues/1989

## Before (pkgdown 2.0.1)

![Screen Shot 2022-01-17 at 2 25 20 PM](https://user-images.githubusercontent.com/216319/149778233-17b8b4f8-be89-481f-8501-b6dc12d2c442.png)
![Screen Shot 2022-01-17 at 2 25 15 PM](https://user-images.githubusercontent.com/216319/149778236-5a7e2236-c23c-45e4-b42d-3377e763a3c6.png)

## After (pkgdown 2.0.2)
![Screen Shot 2022-01-17 at 2 31 54 PM](https://user-images.githubusercontent.com/216319/149778243-ddbad080-d333-4cfb-868f-009f7e8b0543.png)
![Screen Shot 2022-01-17 at 2 31 49 PM](https://user-images.githubusercontent.com/216319/149778244-65487a22-41c6-4fac-9511-0058fae0d573.png)

**Comment by maelle** [comment]
Relevant upstream changes

- https://github.com/r-lib/pkgdown/commit/72200017e36ad6a99706d085699e974ad5b3e417#diff-42da929cc764e94ef6b729b3670bf1f2b086c8906ac4b67b8d0aefaba53133fa
