### ISSUE TITLE
toc style

### ISSUE THREAD

**Issue by jeroen** [ropensci-org/rotemplate#8]
I think the TOC for articles is still a bit large for example [magick vignette](https://maelle.github.io/magick/articles/intro.html). The tidyverse one seems a lot smaller but I'm not sure we can copy that: https://tidyr.tidyverse.org/dev/articles/pivot.html

**Comment by maelle** [comment]
Yeah let me have a look. I had tweaked a param but it was the wrong one, in my vignettes with long titles the titles looked bad. I'll try again :grin:

**Comment by maelle** [comment]
@jeroen I've decreased the line-height and one of the padding parameters. Preview at https://ropenscilabs.github.io/rotemplate/articles/test.html 

I have no further ideas of stuff to tweak, even after looking very closely at the elements with the inspector in both the tidyverse and our template. :cry: Any idea?
