### ISSUE TITLE
Failing test on windows

### ISSUE THREAD

**Issue by jeroen** [ropensci-org/rotemplate#84]
https://github.com/r-universe/ropensci/runs/4937258084?check_suite_focus=true

**Comment by maelle** [comment]
The error is

>   Error: Error: 'C:/Users/runneradmin/AppData/Local/Temp/RtmpcphRV0/file13d861ed268/testPackage/docs/index.html' does not exist.

I do not see anything obvious regarding the paths in the tests. I wonder if it simply means the step before (building the pkgdown website) failed. I wish I could reproduce it in #89. :thinking:
