### ISSUE TITLE
Double logos

### ISSUE THREAD

**Issue by jeroen** [ropensci-org/rotemplate#85]
Due to the changes in https://github.com/ropensci-org/rotemplate/pull/71 many sites now have double logos:

 - https://docs.ropensci.org/medrxivr/
 - https://docs.ropensci.org/mapscanner/
 - https://docs.ropensci.org/osmdata/
 - https://docs.ropensci.org/gert/
 - https://docs.ropensci.org/tidyhydat/
 - https://docs.ropensci.org/credentials/
 - https://docs.ropensci.org/stplanr/
 - https://docs.ropensci.org/rmangal/

**Comment by jeroen** [comment]
I'm starting to think maybe we should be injecting any logos anymore. We have the ropensci logo now in both the navbar and the footer, perhaps that suffices (we were mostly injecting the logo because in the old days our template wasn't so pretty!)

**Comment by maelle** [comment]
> I'm starting to think maybe we should be injecting any logos anymore. We have the ropensci logo now in both the navbar and the footer, perhaps that suffices (we were mostly injecting the logo because in the old days our template wasn't so pretty!)

Fine by me if you decide to do that, otherwise I'd make PRs to the packages above.

**Comment by maelle** [comment]
I'll open PRs in any case, as it might be better for those packages to use logos in a standardized way (so that it appears on more mages). Did you find them randomly?

**Comment by maelle** [comment]
https://github.com/ropensci/mapscanner/commit/3fda376fb8aa76de939bf2eccff3999c528dd436

**Comment by maelle** [comment]
https://github.com/ropensci/osmdata/pull/266

**Comment by jeroen** [comment]
One more: 
https://docs.ropensci.org/refsplitr/
