### ISSUE TITLE
Add head lines with logo etc if removing the logo injection

### ISSUE THREAD

**Issue by maelle** [ropensci-org/rotemplate#88]
For Twitter &co

**Comment by jeroen** [comment]
Ah hmm I didn't realize there was more to it than the h1 logo. What do you think we should do?

**Comment by maelle** [comment]
I'm fine with the logo injection for now to be honest.

If we remove the logo injection we'll still need code to detect a logo à la pkgdown and if it does not exist use an override with the params https://pkgdown.r-lib.org/articles/metadata.html#site-wide-customization to refer to the logo.
