### ISSUE TITLE
Duplicate navbar items?

### ISSUE THREAD

**Issue by jeroen** [ropensci-org/rotemplate#90]
See: https://docs.ropensci.org/tic/

It seems that "get started", "reference" and "changelog" appear twice in the menu bar.

Should they be removed from here? https://github.com/ropensci/tic/blob/main/pkgdown/_pkgdown.yml

**Comment by maelle** [comment]
This is the bug in https://github.com/r-lib/pkgdown/issues/2014

I'll make a PR to tic with the workaround.
