### ISSUE TITLE
URL from `person(comment = "")` not shown on authors page

### ISSUE THREAD

**Issue by dpprdan** [ropensci-org/rotemplate#93]
The [devguide suggests](https://devguide.ropensci.org/building.html#authorship) to add reviewers to the `authors@R` field of the `DESCRIPTION` like so

```
    person("Bea", "Hernández", role = "rev",
    comment = "Bea reviewed the package (v. X.X.XX) for rOpenSci, see <https://github.com/ropensci/software-review/issues/116>"),
```

in particular, to add the URL of the review issue in the `person(comment)` field with angle brackets. 

Unfortunately the URL is not shown on the authors.html page on docs.ropensci.org. See for example https://docs.ropensci.org/opencage/authors.html

![grafik](https://user-images.githubusercontent.com/1423562/173140821-6da99a89-07c0-459f-9aa4-df7a49d361fd.png)

The URL is shown for some other packages (as text, not as a hyperlink), like [bikedata](https://docs.ropensci.org/bikedata/authors.html) or [stplanr](https://docs.ropensci.org/stplanr/authors.html), but only because they do not use angle brackets, see [bikedata's DESCRIPTION](https://github.com/ropensci/bikedata/blob/b2b4a9801cedcdb7333795079660ebd814da55cc/DESCRIPTION#L10-L13).

Apparently this gets by CRAN's bouncers at the moment as [stplanr](https://cran.r-project.org/web/packages/stplanr/index.html) just updated on CRAN. However, [WRE demands](https://cran.r-project.org/doc/manuals/R-exts.html#The-DESCRIPTION-file) angle brackets for URL in other DESCRIPTION fields, so I assume they might be less lenient in the future. 

I suspect that the URL is parsed as an HTML tag because of the angle brackets? Is this something that can be fixed in rotemplate or is this an upstream, i.e. pkgdown issue?

**Comment by maelle** [comment]
Related https://github.com/r-lib/pkgdown/issues/1205

**Comment by maelle** [comment]
Note that this will only be really fixed once pkgdown is released on CRAN and rOpenSci build system has been updated so it might be a little while. 

Thanks a ton for the bug report @dpprdan! :pray:
