### ISSUE TITLE
Add customized link to the forum to the sidebar?

### ISSUE THREAD

**Issue by maelle** [ropensci-org/rotemplate#94]
For instance for magick the link would be https://discuss.ropensci.org/new-topic?category=packages&tags=magick

@jeroen thoughts?

**Comment by jeroen** [comment]
Do we really want this? I much prefer people to open issues in the package repo on github rather than sending them to the forum

**Comment by maelle** [comment]
Even for package use questions?

**Comment by jeroen** [comment]
In my case yes definitely I never look at the forum.

**Comment by maelle** [comment]
Ok fair enough, thank you!
