### ISSUE TITLE
On badges

### ISSUE THREAD

**Issue by maelle** [ropensci-org/rotemplate#95]
@mpadge @jeroen 

pkgdown now no longer includes badges in the sidebar for released website.

How to include software review badges?
- one solution would be to list the software review issue number in the pkgdown config, and rotemplate would use that. It's one more thing to ask authors to do though, and I'd need to open many PRs for existing packages.
- the build process could use the package registry to get that info, put it in the pkgdown config, and the rotemplate template would use that.

Visually, it could be a section like community but called "Software Review" with below the badges + a link to the issue not via the badge.

**Comment by maelle** [comment]
Example

```r
issue_number <- 103
pkgdown::build_site(
  override = list(
    home = list(
      sidebar = list(
        structure = c("links", "license", "community", "citation", "authors", "softwarereview"),
        components = list(
          softwarereview = list(
            title = "Software Peer-Review",
            text = sprintf(
              "[![rOpenSci peer-review](https://badges.ropensci.org/%s_status.svg)](https://github.com/ropensci/software-review/issues/%s)",
              issue_number,
              issue_number
              )
          )
        )
      )
    )
  )
)
```

result

![image](https://user-images.githubusercontent.com/8360597/191236336-e2dc0082-7efc-480c-b19c-b080729e7d13.png)

**Comment by jeroen** [comment]
@maelle I like that! Can we easily add this to `build_ropensci_docs()` in this pkg?

**Comment by maelle** [comment]
yes I'll try that!

**Comment by mpadge** [comment]
I agree - that  looks great !
